
- name: Software Engineering and Technical Architecture
  pitch: Analysis with a report on suggested architecture choices to improve code stability and team productivity
  quote: 3
  about: >
    I have designed the architecture for large websites, HTML5 apps and software as a service platforms.

    These have included:

     - cloud infrastructure using AWS including serverless APIs
     - enterprise CMS builds for Lloyd's of London, British Red Cross and Arrow Electronics
     - campaign sites for The FA and RFU;

    I take a modular approach, I work closely with the development team and other areas of the business to achieve scaleable results.

    I am keen to marry good inter-personal and communication skills with solid technical thought leadership enabling teams to grow in confidence and produce great work.

  rewards:
    - I base my decisions on tried-and-tested solutions
    - I analyse and make the most of current trends
    - I am experienced at communicating and leading teams

