
- id: architecture-analysis
  name: React Application Analysis
  pitch: Analysis of React application architecture
  icon: cogs
  cost: "Codebase: Small £4,800; Med £8,000; Large £800/day"
  period: 2 Weeks
  more: https://www.surveymonkey.co.uk/r/KNN2ZXH
  about: >
    There are many ways in which React Applications can be implemented.

    This analysis report will cover various aspect of how a codebase has
    been structured and coded and will highlight ways it can be improved.

    It also provides insight into tools and testing to give your team the
    insights needed to make each deployment more reliable.

  rewards:
    - Improve code stability
    - How to increase test coverage
    - Tooling

