- id: react-developer
  name: Senior JavaScript React Developer (Contract)
  pitch: >-
    I'll join your team on a contract basis
  icon: cogs
  more: 'mailto:dave.taylor@pogokid.com'
  about: |
    I am based in Bath, England. I can either work from your office within
    the surrounding areas (eg. Bath, Bristol, Cardiff, Chippenham) or remotely
    from my home office and have regular visits.

    I'm happy to visit clients one day a week from offices based slightly further
    away like London, Manchester, Birmingham.

    I have been working with JavaScript applications for over a decade and with
    React, Redux for the last few years.

- id: react-kickoff
  name: React Application Kickoff
  pitch: >-
    Let me start your application with some good choices
  icon: cogs
  more: https://www.surveymonkey.co.uk/r/KNN2ZXH
  about: |
    It's hard to build website applications. There is a steep learning
    curve, many conflicting ideas and complex questions to be answered.

    We have the experience to bring some light into this murky world
    of choices. This report will cover various aspects of setting up a
    codebase, how it should be structured along with documented standards and
    documented coding style guides.

    It also provides insight into tools and testing to give your team the
    insights needed to make each deployment more reliable.

  rewards:
  - Project structure
  - Improve code stability
  - How to increase test coverage
  - Tooling

- id: react-analysis
  name: React Application Analysis
  pitch: >-
    You've already got a React application and want some insight on how
    it could be improved
  icon: cogs
  more: https://www.surveymonkey.co.uk/r/KNN2ZXH
  about: |
    This analysis report will cover various aspect of how a codebase has
    been structured and coded and will highlight ways it can be improved.

    It also provides insight into tools and testing to give your team the
    insights needed to make each deployment more reliable.

  rewards:
    - Project structure
    - Improve code stability
    - How to increase test coverage
    - Tooling

